package controller;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.annotation.*;
import java.io.*;
import java.nio.charset.StandardCharsets;
import com.itextpdf.text.*;
import com.itextpdf.text.pdf.*;
import com.google.gson.*;

@WebServlet("/GeneratePdf")
public class GeneratePdfServlet extends HttpServlet {

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {

        System.out.println("=== GeneratePdf called ===");

        response.setContentType("application/pdf");
        response.setHeader("Content-Disposition", "attachment; filename=health_report.pdf");

        try {
            // Read incoming JSON (same as frontend sends)
            StringBuilder sb = new StringBuilder();
            try (BufferedReader reader = request.getReader()) {
                String line;
                while ((line = reader.readLine()) != null) sb.append(line);
            }

            JsonObject input = JsonParser.parseString(sb.toString()).getAsJsonObject();

            // Extract fields
            String name = input.has("name") ? input.get("name").getAsString() : "User";
            int age = input.has("age") ? input.get("age").getAsInt() : 0;
            int height = input.has("height") ? input.get("height").getAsInt() : 0;
            int weight = input.has("weight") ? input.get("weight").getAsInt() : 0;
            String healthIssues = input.has("healthIssues") ? input.get("healthIssues").getAsString() : "None";
            String suggestions = input.has("suggestions") ? input.get("suggestions").getAsString() : "[No suggestions]";

            // === Create PDF ===
            Document document = new Document(PageSize.A4, 50, 50, 50, 50);
            PdfWriter.getInstance(document, response.getOutputStream());
            document.open();

            // Title
            Font titleFont = new Font(Font.FontFamily.HELVETICA, 20, Font.BOLD, BaseColor.BLUE);
            Paragraph title = new Paragraph("Personalized Health Report", titleFont);
            title.setAlignment(Element.ALIGN_CENTER);
            title.setSpacingAfter(20);
            document.add(title);

            // User Details Section
            Font headerFont = new Font(Font.FontFamily.HELVETICA, 14, Font.BOLD, BaseColor.BLACK);
            Paragraph userHeader = new Paragraph("User Details", headerFont);
            userHeader.setSpacingAfter(10);
            document.add(userHeader);

            Font normalFont = new Font(Font.FontFamily.HELVETICA, 12);
            document.add(new Paragraph("Name: " + name, normalFont));
            document.add(new Paragraph("Age: " + age + " years", normalFont));
            document.add(new Paragraph("Height: " + height + " cm", normalFont));
            document.add(new Paragraph("Weight: " + weight + " kg", normalFont));
            document.add(new Paragraph("Health Issues: " + healthIssues, normalFont));
            document.add(Chunk.NEWLINE);

            // Suggestions Section
            Paragraph sugHeader = new Paragraph("AI Health Suggestions", headerFont);
            sugHeader.setSpacingAfter(10);
            document.add(sugHeader);

            // Add AI output formatted
            Font suggestionFont = new Font(Font.FontFamily.TIMES_ROMAN, 12);
            for (String line : suggestions.split("\n")) {
                if (!line.trim().isEmpty()) {
                    document.add(new Paragraph(line.trim(), suggestionFont));
                }
            }

            document.add(Chunk.NEWLINE);
            document.add(new Paragraph("Generated by HealMe AI Assistant", new Font(Font.FontFamily.COURIER, 10, Font.ITALIC, BaseColor.GRAY)));

            document.close();

            System.out.println(" PDF generated successfully for " + name);

        } catch (Exception e) {
            e.printStackTrace();
            response.setContentType("application/json");
            response.setCharacterEncoding("UTF-8");
            JsonObject error = new JsonObject();
            error.addProperty("ok", false);
            error.addProperty("message", "PDF generation failed: " + e.getMessage());
            response.getWriter().write(error.toString());
        }
    }
}
